name: Build and Deploy Tiles app to GCS

on:
  workflow_call:
    inputs:
      node_base_version:
        description: The Base Node.js version to be used for the build and deploy
        required: false
        type: string
        default: 14.20.1
      project_name:
        description: Name of the application/service
        required: false
        type: string
        default: tiles

permissions:
  actions: read
  checks: write
  contents: write
  id-token: write

jobs:
  ci-test:
    name: ci-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_base_version }}

      - name: CI Tiles Project
        run: npm ci
        shell: bash

      - name: Install Playwright
        run: |
          npm install
          npx playwright install --with-deps
        shell: bash

      - name: Test and CI Tiles Project
        run: |
          export CI=true
          npx playwright test --reporter=line --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        shell: bash

  bump-app-version:
    runs-on: ubuntu-latest
    needs:
      - ci-test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_base_version }}

      - name: Bump Application version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm install
          npm run release
